nodeLinker: node-modules

npmRegistryServer: "https://npm.dev.wixpress.com"

npmMinimalAgeGate: 14d

npmPreapprovedPackages:
  - external-lib-a
  - external-lib-b
  - external-lib-c
  - external-lib-d
  - react-obsidian

packageExtensions:
  "@algolia/autocomplete-core@*":
    peerDependencies:
      "@algolia/client-search": "*"
      algoliasearch: "*"
      search-insights: "*"
  "@algolia/autocomplete-plugin-algolia-insights@*":
    peerDependencies:
      "@algolia/client-search": "*"
      algoliasearch: "*"
  "@docsearch/react@*":
    peerDependencies:
      "@algolia/client-search": "*"
  "@docusaurus/babel@*":
    peerDependencies:
      react: "*"
      react-dom: "*"
  "@docusaurus/bundler@*":
    peerDependencies:
      react: "*"
      react-dom: "*"
  "@docusaurus/plugin-content-blog@*":
    peerDependencies:
      "@mdx-js/react": "*"
  "@docusaurus/plugin-content-docs@*":
    peerDependencies:
      "@mdx-js/react": "*"
  "@docusaurus/plugin-content-pages@*":
    peerDependencies:
      "@mdx-js/react": "*"
  "@docusaurus/plugin-debug@*":
    peerDependencies:
      "@mdx-js/react": "*"
  "@docusaurus/plugin-google-analytics@*":
    peerDependencies:
      "@mdx-js/react": "*"
  "@docusaurus/plugin-google-gtag@*":
    peerDependencies:
      "@mdx-js/react": "*"
  "@docusaurus/plugin-google-tag-manager@*":
    peerDependencies:
      "@mdx-js/react": "*"
  "@docusaurus/plugin-sitemap@*":
    peerDependencies:
      "@mdx-js/react": "*"
  "@docusaurus/plugin-svgr@*":
    peerDependencies:
      "@mdx-js/react": "*"
  "@docusaurus/preset-classic@*":
    peerDependencies:
      "@algolia/client-search": "*"
      "@mdx-js/react": "*"
  "@docusaurus/theme-search-algolia@*":
    peerDependencies:
      "@algolia/client-search": "*"
      "@mdx-js/react": "*"
  "@docusaurus/utils-common@*":
    peerDependencies:
      react: "*"
      react-dom: "*"
  "@docusaurus/utils-validation@*":
    peerDependencies:
      react: "*"
      react-dom: "*"
  "@docusaurus/utils@*":
    peerDependencies:
      react: "*"
      react-dom: "*"
  eslint-config-airbnb-typescript@*:
    peerDependencies:
      eslint-plugin-import: "*"

yarnPath: .yarn/releases/yarn-4.12.0.cjs
