steps:
  - label: ":crossed_swords: Build"
    command: |
      nvm install
      npm install
      npm run test
      if [[ $(echo $BUILDKITE_MESSAGE | tr '[:upper:]' '[:lower:]') =~ release ]];then
        cp .buildkite/.npmrc .
        npm publish
      fi
